# Generated by Django 6.1.1 on 2026-09-05 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('brand_names', models.CharField(blank=True, help_text='Comma-separated common brand names', max_length=300)),
                ('category', models.CharField(blank=True, help_text='e.g. Painkiller, Antibiotic, Antacid', max_length=100)),
                ('used_for', models.TextField(help_text='What condition/symptom this medicine treats')),
                ('common_side_effects', models.TextField(blank=True)),
                ('serious_side_effects', models.TextField(blank=True, help_text='Effects that need urgent medical attention')),
                ('requires_prescription', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('seed', 'Seed data'), ('ai', 'AI-generated'), ('admin', 'Manually added')], default='seed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('safe', 'Generally Safe'), ('caution', 'Use With Caution'), ('avoid', 'Avoid Combination')], max_length=10)),
                ('combined_effects', models.TextField(help_text='What happens if both are taken together')),
                ('explanation', models.TextField(help_text='Why this happens (mechanism)')),
                ('advice', models.TextField(help_text='Practical recommendation: take / avoid / space doses / consult doctor')),
                ('source', models.CharField(choices=[('seed', 'Seed data'), ('ai', 'AI-generated'), ('admin', 'Manually added')], default='seed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_first', to='checker.medicine')),
                ('medicine_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_second', to='checker.medicine')),
            ],
            options={
                'unique_together': {('medicine_1', 'medicine_2')},
            },
        ),
    ]
